const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: ' CHANGE_LANGUAGE',

    //admin
    ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
    ADMIN_LOGIN_FAIL: 'ADMIN_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAIL: 'FETCH_GENDER_FAIL',

    FETCH_POSITION_SUCCESS: 'FETCH_POSITION_SUCCESS',
    FETCH_POSITION_FAIL: 'FETCH_POSITION_FAIL',

    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAIL: 'FETCH_ROLE_FAIL',

    FETCH_POSITION_START: 'FETCH_GENDER_START',
    FETCH_ROLE_START: 'FETCH_GENDER_START',

    CREATE_USER_START: ' CREATE_USER_START',
    CREATE_USER_SUCCESS: ' CREATE_USER_SUCCESS',
    CREATE_USER_FAIL: ' CREATE_USER_FAIL',

    GET_ALL_USER_SUCCESS: 'GET_ALL_USER_SUCCESS',
    GET_ALL_USER_FAIL: 'GET_ALL_USER_FAIL',

    DELETE_USER_START: 'DELETE_USER_START',
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAIL: 'DELETE_USER_FAIL',

    EDIT_USER_START: 'EDIT_USER_START',
    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAIL: 'EDIT_USER_FAIL',


    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCES: 'USER_LOGIN_SUCCES',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',

    //Top Doctor

    FETCH_TOP_DOCTOR_START: 'FETCH_TOP_DOCTOR_START',
    FETCH_TOP_DOCTOR_SUCCESS: 'FETCH_TOP_DOCTOR_SUCCESS',
    FETCH_TOP_DOCTOR_FAIL: 'FETCH_TOP_DOCTOR_FAIL',

    //fech all doctor
    FETCH_ALL_DOCTOR_START: 'FETCH_ALL_DOCTOR_START',
    FETCH_ALL_DOCTOR_SUCCESS: 'FETCH_ALL_DOCTOR_SUCCESS',
    FETCH_ALL_DOCTOR_FAIL: 'FETCH_ALL_DOCTOR_FAIL',

    // create infor doctor
    CREATE_DOCTOR_START: 'CREATE_DOCTOR_START',
    CREATE_DOCTOR_SUCCESS: 'CREATE_DOCTOR_SUCCESS',
    CREATE_DOCTOR_FAIL: 'CREATE_DOCTOR_FAIL',

    //get detail doctor

    GET_DETAIL_DOCTOR_START: ' GET_DETAIL_DOCTOR_START',
    GET_DETAIL_DOCTOR_SUCCESS: ' GET_DETAIL_DOCTOR_SUCCESS',
    GET_DETAIL_DOCTOR_fAIL: ' GET_DETAIL_DOCTOR_fAIL',

    //get Time schedule

    GET_DOCTOR_TIME_SCHEDULE_START: 'GET_DOCTOR_TIME_SCHEDULE_START',
    GET_DOCTOR_TIME_SCHEDULE_SUCCESS: 'GET_DOCTOR_TIME_SCHEDULE_SUCCESS',
    GET_DOCTOR_TIME_SCHEDULE_FAIL: 'GET_DOCTOR_TIME_SCHEDULEFAILT',

    // get price, payment, provine
    GET_REQUIRE_TO_ALLCODE_START: 'GET_REQUIRE_TO_ALLCODE_START',
    GET_REQUIRE_TO_ALLCODE_SUCCESS: 'GET_REQUIRE_TO_ALLCODE_SUCCESS',
    GET_REQUIRE_TO_ALLCODE_FAIL: 'GET_REQUIRE_TO_ALLCODE_FAIL',


})

export default actionTypes;